build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related Prod APIs "
  contactDetails:
    name: "Purushotham - Developer"
    email: "purushotham@eazybank.com"
  onCallSupport:
    - (555) 555-5874
    - (555) 523-1478
