build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Ravi - Developer"
    email: "ravi@eazybank.com"
  onCallSupport:
    - (555) 587-1234
    - (555) 124-1345
